services:
  db-mysql:
    image: mysql:8.0
    container_name: meu-banco-mysql
    restart: always
    environment:
      MYSQL_DATABASE: agiotabank
      MYSQL_ROOT_PASSWORD: senhadoagiotabank
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  agiota-server:
    image: agiota-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agiota-server
    depends_on:
      - db-mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/agiotabank?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: senhadoagiotabank
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    networks:
      - default

volumes:
  mysql-data: